In [2]:
import numpy as np

# Let's makes some Numpy Operations
In this notebook, we will make some operations with Numpy arrays. We will use the following functions:
- Universal functions
- Aggregation functions
- Sorting
- Broadcasting


## Exercise 1 Universal Functions
Given an ndarray x = [4, -1, 7, 9, 3, -5] compute the sigmoid function $ y = sigmoid(x)$ which maps numbers $(-\inf +\inf) \rightarrow (0,1)$

$$ sigmoid(x) = \frac{1}{1 + e^{-x}}$$

In [4]:
def sigmoid(arr: np.array):
    return 1 / (1 + np.exp(arr))

In [5]:
x = np.array([4, -1, 7, 9, 3, -5])
sigmoid(x)

array([1.79862100e-02, 7.31058579e-01, 9.11051194e-04, 1.23394576e-04,
       4.74258732e-02, 9.93307149e-01])

## Exercise 2 Aggregation functions
Given an array
x = [
    [2, 3, -4,],
    [7, 5, 9]
]

Return the mean of the elements along the rows and the minimum element along the columns

In [6]:
x = np.array([
    [2, 3, -4],
    [7, 5, 9]
])

x.mean(axis=1), x.min(axis=0)

(array([0.33333333, 7.        ]), array([ 2,  3, -4]))

## Exercise 3 Sorting
Given the same array as in Ex. 1, i.e., x = [4, -1, 7, 9, 3, -5], find the 3 highest values and the positions of the 2 lowest values

In [9]:
x = np.array([4, -1, 7, 9, 3, -5])
sorted_x = np.sort(x)

sorted_x[-3:]

(array([ 4, -1,  7,  9,  3, -5]), array([-5, -1,  3,  4,  7,  9]))

# Exercise 4 Broadcasting
Compute the product between the array x1 = [[0,1,2], [3,4,5]] and the array x2 = [1, 2]
Does it raise an error? How shall x2 be modified to make the operation possible?


In [3]:
x1 = np.array([[0,1,2], [3,4,5]])
x2 = np.array([1, 2])
x1 * x2

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

The operation raises a `ValueError`, because the two arrays can't be broadcasted together. We could redefine `x2` as:

In [4]:
x2 = np.array([1, 2, 3])
x1 * x2

array([[ 0,  2,  6],
       [ 3,  8, 15]])

## Exercise 5 Broadcasting in practice: centering the features
A dataset is often stored as a matrix with **one row per sample** and **one column per feature**. Given

data = [
    [1, 200],
    [3, 400],
    [5, 900]
]

subtract from every column its mean, so that each feature has mean 0, **without a loop**. Which shapes are involved, and which broadcasting rules apply? Check that the mean of each column of the result is 0.

In [10]:
data = np.array([
    [1, 200],
    [3, 400],
    [5, 900]
])
data - data.mean(axis=0)

array([[  -2., -300.],
       [   0., -100.],
       [   2.,  400.]])